POST http://localhost:5000/users
Content-Type: application/json

{
  "firstName": "User",
  "lastName": "Userenko",
  "email": "user123456@gmail.com",
  "password": "12345admin",
  "isMale": true,
  "balance": 5000,
  "birthday": "1991-01-01"
}